### ISSUE TITLE
TFsec Findings Explorer window use causes UI issues.

### ISSUE THREAD

**Issue by devsecopshomelearning** [aquasecurity/intellij-tfsec#4]
Issue: 
Attempting to use TFsec Findings Explorer triggers null pointer error.  After the error is triggered misc. UI issues begin to occur and will normally spike the CPU usage and prevent typical program closure methods. This has happened multiple times including after uninstall reinstall of the plugin and rebooting the device. So far I have been unable to get the plugin to function as desired, I still have access to the binary and will use that in the mean time. Please take a look when you can.

Issue Error Trace:
`java.lang.NullPointerException at com.aquasecurity.plugins.tfsec.model.Findings.setBasePath(Findings.java:19) at com.aquasecurity.plugins.tfsec.ui.TfsecWindow.updateFindings(TfsecWindow.java:71) at com.aquasecurity.plugins.tfsec.actions.ResultProcessor.updateResults(ResultProcessor.java:35) at com.aquasecurity.plugins.tfsec.actions.TfsecBackgroundRunTask.lambda$run$0(TfsecBackgroundRunTask.java:66) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760) at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447) at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818) at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446) at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by owenrumney** [comment]
Hey @devsecopshomelearning  - this should be resolved in v1.1.0 which is currently going through Jetbrains approval process
